spring.application.name=tablelink

spring.datasource.url=jdbc:postgresql://localhost:5432/tablelink
spring.datasource.username=tablelink
spring.datasource.password=tablelink

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
